name: Create PR from master to release/production
on:
  push:
    branches:
      - master
jobs:
  gitPrRelease:
    name: pr-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
        with:
          fetch-depth: 0
      - name: create-pr
        uses: bakunyo/git-pr-release-action@1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_STAGING: master
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release/production
          GIT_PR_RELEASE_TEMPLATE: .github/templates/release-pr.erb
          TZ: America/Bogota
